import { Product, Category, Scheme } from "./types/catalog"
import { subDays, addDays } from "date-fns"

// Categories
export const categories: Category[] = [
  { id: "cat-1", name: "Beverages", parentId: null, level: 0, productCount: 203 },
  { id: "cat-2", name: "Soft Drinks", parentId: "cat-1", level: 1, productCount: 125 },
  { id: "cat-3", name: "Juices", parentId: "cat-1", level: 1, productCount: 78 },
  { id: "cat-4", name: "Personal Care", parentId: null, level: 0, productCount: 145 },
  { id: "cat-5", name: "Shampoos", parentId: "cat-4", level: 1, productCount: 45 },
  { id: "cat-6", name: "Soaps", parentId: "cat-4", level: 1, productCount: 32 },
  { id: "cat-7", name: "Snacks", parentId: null, level: 0, productCount: 312 },
  { id: "cat-8", name: "Chips", parentId: "cat-7", level: 1, productCount: 89 },
  { id: "cat-9", name: "Biscuits", parentId: "cat-7", level: 1, productCount: 156 },
]

// Products
export const products: Product[] = [
  {
    id: "p1",
    name: "Coca Cola",
    sku: "COKE-001",
    category: "Beverages > Soft Drinks",
    categoryId: "cat-2",
    description: "Classic Coca Cola soft drink",
    basePrice: 40,
    packaging: "PET Bottle",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v1", name: "250ml", sku: "COKE-001-250", price: 20, stock: true },
      { id: "v2", name: "500ml", sku: "COKE-001-500", price: 40, stock: true },
      { id: "v3", name: "1L", sku: "COKE-001-1L", price: 70, stock: true },
      { id: "v4", name: "2L", sku: "COKE-001-2L", price: 120, stock: false },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-20"),
  },
  {
    id: "p2",
    name: "Pepsi",
    sku: "PEPSI-001",
    category: "Beverages > Soft Drinks",
    categoryId: "cat-2",
    description: "Refreshing Pepsi cola",
    basePrice: 40,
    packaging: "PET Bottle",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v5", name: "250ml", sku: "PEPSI-001-250", price: 20, stock: true },
      { id: "v6", name: "500ml", sku: "PEPSI-001-500", price: 40, stock: true },
      { id: "v7", name: "1L", sku: "PEPSI-001-1L", price: 70, stock: true },
      { id: "v8", name: "2L", sku: "PEPSI-001-2L", price: 120, stock: true },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-18"),
  },
  {
    id: "p3",
    name: "Lays Classic Salted",
    sku: "LAYS-001",
    category: "Snacks > Chips",
    categoryId: "cat-8",
    description: "Classic salted potato chips",
    basePrice: 10,
    packaging: "Packet",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v9", name: "25g", sku: "LAYS-001-25", price: 10, stock: true },
      { id: "v10", name: "50g", sku: "LAYS-001-50", price: 20, stock: true },
      { id: "v11", name: "100g", sku: "LAYS-001-100", price: 40, stock: true },
    ],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-10-15"),
  },
  {
    id: "p4",
    name: "Sunsilk Shampoo",
    sku: "SUNS-001",
    category: "Personal Care > Shampoos",
    categoryId: "cat-5",
    description: "Sunsilk Black Shine shampoo",
    basePrice: 85,
    packaging: "Bottle",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v12", name: "180ml", sku: "SUNS-001-180", price: 85, stock: true },
      { id: "v13", name: "360ml", sku: "SUNS-001-360", price: 150, stock: true },
      { id: "v14", name: "650ml", sku: "SUNS-001-650", price: 250, stock: true },
    ],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-10-22"),
  },
  {
    id: "p5",
    name: "Dettol Soap",
    sku: "DETT-001",
    category: "Personal Care > Soaps",
    categoryId: "cat-6",
    description: "Dettol antiseptic soap",
    basePrice: 35,
    packaging: "Bar",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v15", name: "75g", sku: "DETT-001-75", price: 35, stock: true },
      { id: "v16", name: "125g", sku: "DETT-001-125", price: 55, stock: true },
      { id: "v17", name: "Pack of 3", sku: "DETT-001-P3", price: 150, stock: true },
    ],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-10-19"),
  },
  {
    id: "p6",
    name: "Tropicana Orange Juice",
    sku: "TROP-001",
    category: "Beverages > Juices",
    categoryId: "cat-3",
    description: "100% orange juice",
    basePrice: 50,
    packaging: "Tetra Pack",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v18", name: "200ml", sku: "TROP-001-200", price: 30, stock: true },
      { id: "v19", name: "500ml", sku: "TROP-001-500", price: 50, stock: true },
      { id: "v20", name: "1L", sku: "TROP-001-1L", price: 95, stock: true },
    ],
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-10-21"),
  },
  {
    id: "p7",
    name: "Parle-G Biscuits",
    sku: "PARL-001",
    category: "Snacks > Biscuits",
    categoryId: "cat-9",
    description: "Classic glucose biscuits",
    basePrice: 5,
    packaging: "Pack",
    stockAvailable: true,
    isActive: true,
    images: [],
    variants: [
      { id: "v21", name: "82g", sku: "PARL-001-82", price: 5, stock: true },
      { id: "v22", name: "200g", sku: "PARL-001-200", price: 12, stock: true },
      { id: "v23", name: "500g", sku: "PARL-001-500", price: 28, stock: true },
    ],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "p8",
    name: "Sprite",
    sku: "SPRI-001",
    category: "Beverages > Soft Drinks",
    categoryId: "cat-2",
    description: "Lemon-lime flavored drink",
    basePrice: 40,
    packaging: "PET Bottle",
    stockAvailable: false,
    isActive: true,
    images: [],
    variants: [
      { id: "v24", name: "250ml", sku: "SPRI-001-250", price: 20, stock: false },
      { id: "v25", name: "500ml", sku: "SPRI-001-500", price: 40, stock: false },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-16"),
  },
]

// Schemes
export const schemes: Scheme[] = [
  {
    id: "s1",
    name: "Coca Cola Buy 10 Get 2",
    type: "quantity",
    status: "active",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    details: {
      product: { id: "p1", name: "Coca Cola 500ml" },
      buyQuantity: 10,
      freeQuantity: 2,
    },
    performance: {
      timesUsed: 127,
      totalSavings: 240000,
      topReps: ["Rahul", "Priya", "Amit"],
    },
    autoApply: true,
    categories: ["Beverages"],
  },
  {
    id: "s2",
    name: "Lays Festive Offer",
    type: "quantity",
    status: "active",
    startDate: new Date("2024-10-15"),
    endDate: new Date("2024-11-15"),
    details: {
      product: { id: "p3", name: "Lays Classic 50g" },
      buyQuantity: 20,
      freeQuantity: 5,
    },
    performance: {
      timesUsed: 89,
      totalSavings: 125000,
      topReps: ["Priya", "Vikram", "Sneha"],
    },
    autoApply: true,
    categories: ["Snacks"],
  },
  {
    id: "s3",
    name: "Shampoo + Conditioner Combo",
    type: "cross_product",
    status: "active",
    startDate: new Date("2024-10-01"),
    endDate: addDays(new Date(), 5),
    details: {
      product: { id: "p4", name: "Sunsilk Shampoo 360ml" },
      buyQuantity: 5,
      crossProduct: { id: "p-cond", name: "Sunsilk Conditioner 180ml" },
      freeQuantity: 1,
    },
    performance: {
      timesUsed: 64,
      totalSavings: 85000,
      topReps: ["Anjali", "Rahul", "Kavita"],
    },
    autoApply: true,
    categories: ["Personal Care"],
  },
  {
    id: "s4",
    name: "₹5000+ Order Discount",
    type: "order_value",
    status: "active",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-12-31"),
    details: {
      minOrderValue: 5000,
      discountType: "percentage",
      discountValue: 10,
    },
    performance: {
      timesUsed: 234,
      totalSavings: 890000,
      topReps: ["Rahul", "Priya", "Amit"],
    },
    autoApply: true,
    categories: [],
  },
  {
    id: "s5",
    name: "Diwali Special - Pepsi",
    type: "quantity",
    status: "expiring",
    startDate: subDays(new Date(), 20),
    endDate: addDays(new Date(), 3),
    details: {
      product: { id: "p2", name: "Pepsi 1L" },
      buyQuantity: 12,
      freeQuantity: 3,
    },
    performance: {
      timesUsed: 156,
      totalSavings: 320000,
      topReps: ["Vikram", "Sneha", "Rajesh"],
    },
    autoApply: true,
    categories: ["Beverages"],
  },
  {
    id: "s6",
    name: "Summer Juice Bonanza",
    type: "quantity",
    status: "inactive",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-07-31"),
    details: {
      product: { id: "p6", name: "Tropicana Orange 1L" },
      buyQuantity: 6,
      freeQuantity: 1,
    },
    performance: {
      timesUsed: 412,
      totalSavings: 450000,
      topReps: ["Priya", "Amit", "Anjali"],
    },
    autoApply: false,
    categories: ["Beverages"],
  },
]

// Calculate catalog metrics
export const catalogMetrics = {
  totalProducts: products.length,
  activeProducts: products.filter((p) => p.isActive).length,
  totalCategories: categories.length,
  totalVariants: products.reduce((sum, p) => sum + p.variants.length, 0),
}

// Calculate scheme metrics
export const schemeMetrics = {
  activeSchemes: schemes.filter((s) => s.status === "active").length,
  expiringSchemes: schemes.filter((s) => s.status === "expiring").length,
  totalMentions: schemes.reduce((sum, s) => sum + s.performance.timesUsed, 0),
  avgDiscount: 15,
}
