import { Customer, CustomerMetrics } from "./types/customers"
import { subDays, subMonths } from "date-fns"

export const customers: Customer[] = [
  {
    id: "c1",
    name: "ABC Corporation Ltd",
    contactPerson: "Rajesh Kumar",
    phone: "+91-98765-43210",
    email: "rajesh@abccorp.com",
    address: "Plot 123, Andheri East",
    city: "Mumbai",
    gstNumber: "27AABCU9603R1ZM",
    creditLimit: 500000,
    outstanding: 125000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 2),
    tallyId: "CUST-001",
    createdAt: new Date("2023-06-15"),
    activities: [
      {
        type: "visit",
        date: subDays(new Date(), 2),
        rep: "Rahul Sharma",
        outcome: "Sale Closed",
      },
      {
        type: "call",
        date: subDays(new Date(), 5),
        rep: "Priya Patel",
        outcome: "Interested",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 8),
        amount: 50000,
        method: "Bank Transfer",
        invoiceNumber: "INV-2024-001",
      },
      {
        date: subDays(new Date(), 25),
        amount: 75000,
        method: "Cheque",
        invoiceNumber: "INV-2024-002",
      },
    ],
    orders: [
      {
        id: "ORD-001",
        date: subDays(new Date(), 2),
        amount: 75000,
        status: "delivered",
        products: ["Coca Cola 500ml", "Lays Classic 50g"],
      },
    ],
  },
  {
    id: "c2",
    name: "Sharma General Store",
    contactPerson: "Amit Sharma",
    phone: "+91-98765-12345",
    email: "amit@sharmastore.com",
    address: "Shop 45, Connaught Place",
    city: "Delhi",
    gstNumber: "07AABCS1234F1Z5",
    creditLimit: 300000,
    outstanding: 85000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 1),
    tallyId: "CUST-002",
    createdAt: new Date("2023-03-20"),
    activities: [
      {
        type: "call",
        date: subDays(new Date(), 1),
        rep: "Vikram Singh",
        outcome: "Callback",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 12),
        amount: 40000,
        method: "UPI",
        invoiceNumber: "INV-2024-003",
      },
    ],
    orders: [
      {
        id: "ORD-002",
        date: subDays(new Date(), 5),
        amount: 45000,
        status: "delivered",
        products: ["Pepsi 1L", "Parle-G Biscuits"],
      },
    ],
  },
  {
    id: "c3",
    name: "City Mart Retail",
    contactPerson: "Priya Menon",
    phone: "+91-98765-67890",
    email: "priya@citymart.com",
    address: "MG Road, Koramangala",
    city: "Bangalore",
    gstNumber: "29AABCC5678D1Z8",
    creditLimit: 800000,
    outstanding: 250000,
    paymentTerms: "45 days",
    status: "active",
    lastActivity: subDays(new Date(), 3),
    tallyId: "CUST-003",
    createdAt: new Date("2022-11-10"),
    activities: [
      {
        type: "meeting",
        date: subDays(new Date(), 3),
        rep: "Anjali Desai",
        outcome: "Meeting Scheduled",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 15),
        amount: 120000,
        method: "Bank Transfer",
        invoiceNumber: "INV-2024-004",
      },
    ],
    orders: [
      {
        id: "ORD-003",
        date: subDays(new Date(), 10),
        amount: 150000,
        status: "delivered",
        products: ["Sunsilk Shampoo 360ml", "Dettol Soap"],
      },
    ],
  },
  {
    id: "c4",
    name: "Kumar Enterprises",
    contactPerson: "Suresh Kumar",
    phone: "+91-98765-11111",
    email: "suresh@kumarenterprises.com",
    address: "T Nagar, Anna Salai",
    city: "Chennai",
    gstNumber: "33AABCK9012E1Z1",
    creditLimit: 400000,
    outstanding: 95000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 7),
    tallyId: "CUST-004",
    createdAt: new Date("2023-01-05"),
    activities: [
      {
        type: "email",
        date: subDays(new Date(), 7),
        rep: "Sneha Reddy",
        outcome: "Interested",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 20),
        amount: 60000,
        method: "Cash",
        invoiceNumber: "INV-2024-005",
      },
    ],
    orders: [
      {
        id: "ORD-004",
        date: subDays(new Date(), 15),
        amount: 80000,
        status: "delivered",
        products: ["Tropicana Orange 1L"],
      },
    ],
  },
  {
    id: "c5",
    name: "Modern Trade Co",
    contactPerson: "Kavita Iyer",
    phone: "+91-98765-22222",
    email: "kavita@moderntrade.com",
    address: "Shivaji Nagar, FC Road",
    city: "Pune",
    gstNumber: "27AABCM3456F1Z9",
    creditLimit: 600000,
    outstanding: 180000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 4),
    tallyId: "CUST-005",
    createdAt: new Date("2023-07-12"),
    activities: [
      {
        type: "visit",
        date: subDays(new Date(), 4),
        rep: "Rahul Sharma",
        outcome: "Sale Closed",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 10),
        amount: 90000,
        method: "Bank Transfer",
        invoiceNumber: "INV-2024-006",
      },
    ],
    orders: [
      {
        id: "ORD-005",
        date: subDays(new Date(), 4),
        amount: 120000,
        status: "delivered",
        products: ["Coca Cola 500ml", "Sprite"],
      },
    ],
  },
  {
    id: "c6",
    name: "Patel Brothers",
    contactPerson: "Kiran Patel",
    phone: "+91-98765-33333",
    email: "kiran@patelbrothers.com",
    address: "CG Road, Navrangpura",
    city: "Ahmedabad",
    gstNumber: "24AABCP7890G1Z2",
    creditLimit: 350000,
    outstanding: 70000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 6),
    tallyId: "CUST-006",
    createdAt: new Date("2023-04-18"),
    activities: [
      {
        type: "call",
        date: subDays(new Date(), 6),
        rep: "Priya Patel",
        outcome: "Callback",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 14),
        amount: 35000,
        method: "UPI",
        invoiceNumber: "INV-2024-007",
      },
    ],
    orders: [
      {
        id: "ORD-006",
        date: subDays(new Date(), 12),
        amount: 55000,
        status: "delivered",
        products: ["Lays Classic 50g", "Parle-G Biscuits"],
      },
    ],
  },
  {
    id: "c7",
    name: "Premium Stores Ltd",
    contactPerson: "Ankit Gupta",
    phone: "+91-98765-44444",
    email: "ankit@premiumstores.com",
    address: "Banjara Hills, Road No. 12",
    city: "Hyderabad",
    gstNumber: "36AABCP1234H1Z3",
    creditLimit: 700000,
    outstanding: 210000,
    paymentTerms: "45 days",
    status: "active",
    lastActivity: subDays(new Date(), 5),
    tallyId: "CUST-007",
    createdAt: new Date("2022-09-25"),
    activities: [
      {
        type: "meeting",
        date: subDays(new Date(), 5),
        rep: "Vikram Singh",
        outcome: "Sale Closed",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 18),
        amount: 105000,
        method: "Cheque",
        invoiceNumber: "INV-2024-008",
      },
    ],
    orders: [
      {
        id: "ORD-007",
        date: subDays(new Date(), 8),
        amount: 140000,
        status: "delivered",
        products: ["Sunsilk Shampoo 360ml", "Dettol Soap"],
      },
    ],
  },
  {
    id: "c8",
    name: "Metro Retail Chain",
    contactPerson: "Ravi Shankar",
    phone: "+91-98765-55555",
    email: "ravi@metroretail.com",
    address: "Park Street, Esplanade",
    city: "Kolkata",
    gstNumber: "19AABCM5678I1Z4",
    creditLimit: 550000,
    outstanding: 165000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 8),
    tallyId: "CUST-008",
    createdAt: new Date("2023-02-14"),
    activities: [
      {
        type: "email",
        date: subDays(new Date(), 8),
        rep: "Anjali Desai",
        outcome: "Interested",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 22),
        amount: 82000,
        method: "Bank Transfer",
        invoiceNumber: "INV-2024-009",
      },
    ],
    orders: [
      {
        id: "ORD-008",
        date: subDays(new Date(), 18),
        amount: 95000,
        status: "delivered",
        products: ["Pepsi 1L", "Tropicana Orange 1L"],
      },
    ],
  },
  {
    id: "c9",
    name: "Green Valley Stores",
    contactPerson: "Meera Nair",
    phone: "+91-98765-66666",
    email: "meera@greenvalley.com",
    address: "MG Road, Marine Drive",
    city: "Kochi",
    gstNumber: "32AABCG4567J1Z5",
    creditLimit: 250000,
    outstanding: 45000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 10),
    tallyId: "CUST-009",
    createdAt: new Date("2023-08-30"),
    activities: [
      {
        type: "call",
        date: subDays(new Date(), 10),
        rep: "Sneha Reddy",
        outcome: "Callback",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 16),
        amount: 25000,
        method: "UPI",
        invoiceNumber: "INV-2024-010",
      },
    ],
    orders: [
      {
        id: "ORD-009",
        date: subDays(new Date(), 20),
        amount: 35000,
        status: "delivered",
        products: ["Coca Cola 500ml"],
      },
    ],
  },
  {
    id: "c10",
    name: "Royal Supermarket",
    contactPerson: "Arjun Rao",
    phone: "+91-98765-77777",
    email: "arjun@royalsupermarket.com",
    address: "Jubilee Hills, Road No. 36",
    city: "Hyderabad",
    gstNumber: "36AABCR6789K1Z6",
    creditLimit: 450000,
    outstanding: 135000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 3),
    tallyId: "CUST-010",
    createdAt: new Date("2023-05-22"),
    activities: [
      {
        type: "visit",
        date: subDays(new Date(), 3),
        rep: "Rahul Sharma",
        outcome: "Sale Closed",
      },
    ],
    payments: [
      {
        date: subDays(new Date(), 11),
        amount: 68000,
        method: "Bank Transfer",
        invoiceNumber: "INV-2024-011",
      },
    ],
    orders: [
      {
        id: "ORD-010",
        date: subDays(new Date(), 7),
        amount: 88000,
        status: "delivered",
        products: ["Lays Classic 50g", "Sprite"],
      },
    ],
  },
  // Add more customers with varied data
  {
    id: "c11",
    name: "Quick Shop Retail",
    contactPerson: "Neha Kapoor",
    phone: "+91-98765-88888",
    email: "neha@quickshop.com",
    address: "Saket, Main Market",
    city: "Delhi",
    creditLimit: 200000,
    outstanding: 15000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 12),
    tallyId: "CUST-011",
    createdAt: subMonths(new Date(), 2),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c12",
    name: "Star Traders",
    contactPerson: "Deepak Verma",
    phone: "+91-98765-99999",
    email: "deepak@startraders.com",
    address: "Malviya Nagar, Commercial Complex",
    city: "Jaipur",
    creditLimit: 300000,
    outstanding: 55000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 9),
    createdAt: new Date("2023-06-01"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c13",
    name: "Sunrise Stores",
    contactPerson: "Lakshmi Iyer",
    phone: "+91-98766-11111",
    email: "lakshmi@sunrisestores.com",
    address: "Anna Nagar, West Extension",
    city: "Chennai",
    creditLimit: 350000,
    outstanding: 78000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 14),
    createdAt: new Date("2023-03-15"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c14",
    name: "Elite Provisions",
    contactPerson: "Sanjay Malhotra",
    phone: "+91-98766-22222",
    email: "sanjay@eliteprovisions.com",
    address: "Model Town, Central Market",
    city: "Ludhiana",
    creditLimit: 280000,
    outstanding: 62000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 11),
    createdAt: new Date("2023-07-20"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c15",
    name: "Happy Mart",
    contactPerson: "Pooja Agarwal",
    phone: "+91-98766-33333",
    email: "pooja@happymart.com",
    address: "Hazratganj, Main Road",
    city: "Lucknow",
    creditLimit: 220000,
    outstanding: 38000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 16),
    createdAt: new Date("2023-09-10"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c16",
    name: "Golden Traders",
    contactPerson: "Vikash Jain",
    phone: "+91-98766-44444",
    email: "vikash@goldentraders.com",
    address: "Thaltej, SG Highway",
    city: "Ahmedabad",
    creditLimit: 400000,
    outstanding: 98000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 5),
    createdAt: new Date("2022-12-05"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c17",
    name: "City Center Stores",
    contactPerson: "Ramesh Pillai",
    phone: "+91-98766-55555",
    email: "ramesh@citycenter.com",
    address: "Viman Nagar, Main Street",
    city: "Pune",
    creditLimit: 320000,
    outstanding: 72000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 13),
    createdAt: new Date("2023-04-25"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c18",
    name: "Metro Bazaar",
    contactPerson: "Geeta Singh",
    phone: "+91-98766-66666",
    email: "geeta@metrobazaar.com",
    address: "Aliganj, Sector A",
    city: "Lucknow",
    creditLimit: 260000,
    outstanding: 48000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 18),
    createdAt: new Date("2023-08-14"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c19",
    name: "Super Saver Stores",
    contactPerson: "Manish Tiwari",
    phone: "+91-98766-77777",
    email: "manish@supersaver.com",
    address: "Indira Nagar, Lucknow Road",
    city: "Kanpur",
    creditLimit: 190000,
    outstanding: 32000,
    paymentTerms: "15 days",
    status: "active",
    lastActivity: subDays(new Date(), 20),
    createdAt: new Date("2023-10-01"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c20",
    name: "Fresh Mart",
    contactPerson: "Shruti Deshmukh",
    phone: "+91-98766-88888",
    email: "shruti@freshmart.com",
    address: "Rajapark, Tonk Road",
    city: "Jaipur",
    creditLimit: 275000,
    outstanding: 58000,
    paymentTerms: "30 days",
    status: "active",
    lastActivity: subDays(new Date(), 15),
    createdAt: new Date("2023-05-18"),
    activities: [],
    payments: [],
    orders: [],
  },
  // Inactive customers
  {
    id: "c21",
    name: "Old City Stores",
    contactPerson: "Ramakrishnan S",
    phone: "+91-98767-11111",
    email: "ramakrishnan@oldcity.com",
    address: "Mylapore, Kutchery Road",
    city: "Chennai",
    creditLimit: 150000,
    outstanding: 0,
    paymentTerms: "30 days",
    status: "inactive",
    lastActivity: subDays(new Date(), 65),
    createdAt: new Date("2022-08-10"),
    activities: [],
    payments: [],
    orders: [],
  },
  {
    id: "c22",
    name: "Heritage Traders",
    contactPerson: "Ashok Kumar",
    phone: "+91-98767-22222",
    email: "ashok@heritagetraders.com",
    address: "Charminar, Old City",
    city: "Hyderabad",
    creditLimit: 180000,
    outstanding: 0,
    paymentTerms: "15 days",
    status: "inactive",
    lastActivity: subDays(new Date(), 95),
    createdAt: new Date("2022-05-15"),
    activities: [],
    payments: [],
    orders: [],
  },
]

export const customerMetrics: CustomerMetrics = {
  totalCustomers: 156,
  activeCustomers: 142,
  highValueCustomers: 23,
  newThisMonth: 8,
}

export const cities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Pune",
  "Ahmedabad",
  "Hyderabad",
  "Kolkata",
  "Kochi",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Ludhiana",
]
