import { subDays, addDays } from "date-fns"
import { OutstandingPayment } from "./types/payments"
import { calculateAgingDays, getAgingBucket } from "./utils"

// Comprehensive outstanding payments data
export const outstandingPaymentsData: OutstandingPayment[] = [
  {
    id: "1",
    customer: {
      id: "c1",
      name: "ABC Corporation Ltd",
      contactPerson: "Rajesh Kumar",
      phone: "+91-98765-43210",
      email: "rajesh@abccorp.com",
    },
    invoices: ["INV-2024-001", "INV-2024-015"],
    amount: 185000,
    dueDate: subDays(new Date(), 45),
    agingDays: 45,
    agingBucket: "30-60 days",
    lastReminder: subDays(new Date(), 5),
    status: "overdue",
    paymentHistory: [
      { date: subDays(new Date(), 60), amount: 50000, method: "Bank Transfer" },
    ],
  },
  {
    id: "2",
    customer: {
      id: "c2",
      name: "XYZ Industries Pvt Ltd",
      contactPerson: "Priya Sharma",
      phone: "+91-99887-76655",
      email: "priya@xyzindustries.in",
    },
    invoices: ["INV-2024-023"],
    amount: 320000,
    dueDate: subDays(new Date(), 95),
    agingDays: 95,
    agingBucket: "90+ days",
    lastReminder: subDays(new Date(), 10),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "3",
    customer: {
      id: "c3",
      name: "PQR Traders",
      contactPerson: "Amit Patel",
      phone: "+91-98123-45678",
      email: "amit@pqrtraders.com",
    },
    invoices: ["INV-2024-045"],
    amount: 95000,
    dueDate: subDays(new Date(), 15),
    agingDays: 15,
    agingBucket: "0-30 days",
    lastReminder: subDays(new Date(), 3),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "4",
    customer: {
      id: "c4",
      name: "LMN Enterprises",
      contactPerson: "Sneha Desai",
      phone: "+91-97654-32109",
      email: "sneha@lmnenterprises.in",
    },
    invoices: ["INV-2024-012", "INV-2024-034", "INV-2024-056"],
    amount: 450000,
    dueDate: subDays(new Date(), 105),
    agingDays: 105,
    agingBucket: "90+ days",
    lastReminder: subDays(new Date(), 7),
    status: "overdue",
    paymentHistory: [
      { date: subDays(new Date(), 120), amount: 100000, method: "Cheque" },
    ],
  },
  {
    id: "5",
    customer: {
      id: "c5",
      name: "Supreme Textiles",
      contactPerson: "Vikram Singh",
      phone: "+91-99000-11222",
      email: "vikram@supremetextiles.com",
    },
    invoices: ["INV-2024-067"],
    amount: 125000,
    dueDate: addDays(new Date(), 10),
    agingDays: -10,
    agingBucket: "Not due",
    lastReminder: null,
    status: "current",
    paymentHistory: [],
  },
  {
    id: "6",
    customer: {
      id: "c6",
      name: "Metro Manufacturing Co",
      contactPerson: "Anjali Verma",
      phone: "+91-98777-66544",
      email: "anjali@metromanufacturing.in",
    },
    invoices: ["INV-2024-089"],
    amount: 275000,
    dueDate: subDays(new Date(), 22),
    agingDays: 22,
    agingBucket: "0-30 days",
    lastReminder: subDays(new Date(), 2),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "7",
    customer: {
      id: "c7",
      name: "Global Tech Solutions",
      contactPerson: "Rohan Gupta",
      phone: "+91-96543-21098",
      email: "rohan@globaltechsolutions.com",
    },
    invoices: ["INV-2024-101"],
    amount: 340000,
    dueDate: addDays(new Date(), 5),
    agingDays: -5,
    agingBucket: "Not due",
    lastReminder: null,
    status: "due_soon",
    paymentHistory: [
      { date: subDays(new Date(), 30), amount: 150000, method: "UPI" },
    ],
  },
  {
    id: "8",
    customer: {
      id: "c8",
      name: "Sunshine Retailers",
      contactPerson: "Kavita Menon",
      phone: "+91-99111-22333",
      email: "kavita@sunshineretailers.in",
    },
    invoices: ["INV-2024-078"],
    amount: 88000,
    dueDate: subDays(new Date(), 8),
    agingDays: 8,
    agingBucket: "0-30 days",
    lastReminder: subDays(new Date(), 1),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "9",
    customer: {
      id: "c9",
      name: "Royal Distributors",
      contactPerson: "Sanjay Malhotra",
      phone: "+91-98222-33444",
      email: "sanjay@royaldistributors.com",
    },
    invoices: ["INV-2024-092"],
    amount: 215000,
    dueDate: subDays(new Date(), 38),
    agingDays: 38,
    agingBucket: "30-60 days",
    lastReminder: subDays(new Date(), 4),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "10",
    customer: {
      id: "c10",
      name: "Modern Supplies Ltd",
      contactPerson: "Deepak Joshi",
      phone: "+91-97333-44555",
      email: "deepak@modernsupplies.in",
    },
    invoices: ["INV-2024-105"],
    amount: 165000,
    dueDate: addDays(new Date(), 15),
    agingDays: -15,
    agingBucket: "Not due",
    lastReminder: null,
    status: "current",
    paymentHistory: [],
  },
  {
    id: "11",
    customer: {
      id: "c11",
      name: "Elite Trading Co",
      contactPerson: "Meera Reddy",
      phone: "+91-96444-55666",
      email: "meera@elitetrading.com",
    },
    invoices: ["INV-2024-087", "INV-2024-098"],
    amount: 395000,
    dueDate: subDays(new Date(), 52),
    agingDays: 52,
    agingBucket: "30-60 days",
    lastReminder: subDays(new Date(), 6),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "12",
    customer: {
      id: "c12",
      name: "Premier Goods Ltd",
      contactPerson: "Anil Kumar",
      phone: "+91-95555-66777",
      email: "anil@premiergoods.in",
    },
    invoices: ["INV-2024-110"],
    amount: 142000,
    dueDate: subDays(new Date(), 28),
    agingDays: 28,
    agingBucket: "0-30 days",
    lastReminder: null,
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "13",
    customer: {
      id: "c13",
      name: "Mega Mart Pvt Ltd",
      contactPerson: "Pooja Singh",
      phone: "+91-94666-77888",
      email: "pooja@megamart.com",
    },
    invoices: ["INV-2024-115"],
    amount: 385000,
    dueDate: addDays(new Date(), 20),
    agingDays: -20,
    agingBucket: "Not due",
    lastReminder: null,
    status: "current",
    paymentHistory: [],
  },
  {
    id: "14",
    customer: {
      id: "c14",
      name: "City Wholesalers",
      contactPerson: "Rahul Mehta",
      phone: "+91-93777-88999",
      email: "rahul@citywholesalers.in",
    },
    invoices: ["INV-2024-099"],
    amount: 98000,
    dueDate: subDays(new Date(), 12),
    agingDays: 12,
    agingBucket: "0-30 days",
    lastReminder: subDays(new Date(), 1),
    status: "overdue",
    paymentHistory: [],
  },
  {
    id: "15",
    customer: {
      id: "c15",
      name: "Star Industries",
      contactPerson: "Neha Kapoor",
      phone: "+91-92888-99000",
      email: "neha@starindustries.com",
    },
    invoices: ["INV-2024-081"],
    amount: 228000,
    dueDate: subDays(new Date(), 75),
    agingDays: 75,
    agingBucket: "60-90 days",
    lastReminder: subDays(new Date(), 8),
    status: "overdue",
    paymentHistory: [],
  },
]

// Calculate payment metrics
export const paymentMetrics = {
  totalOutstanding: outstandingPaymentsData.reduce((sum, p) => sum + p.amount, 0),
  overdueAmount: outstandingPaymentsData
    .filter((p) => p.status === "overdue")
    .reduce((sum, p) => sum + p.amount, 0),
  overdueCount: outstandingPaymentsData.filter((p) => p.status === "overdue").length,
  dueThisWeek: outstandingPaymentsData
    .filter((p) => p.agingDays >= -7 && p.agingDays <= 0)
    .reduce((sum, p) => sum + p.amount, 0),
  dueThisWeekCount: outstandingPaymentsData.filter(
    (p) => p.agingDays >= -7 && p.agingDays <= 0
  ).length,
  collectionRate: 78, // Mock collection rate
}
